// Curated trending mods for Surron, Talaria, and light electric bikes

export const MODS = [
  // ── BRAKES ─────────────────────────────────────────────────────
  {id:"brake-ultrabee-kit",title:"Surron Ultra Bee Hydraulic Brake Upgrade Kit",brand:"Magura",category:"brakes",trending:10,retail_price:320,found_price:195,description:"Full hydraulic brake upgrade kit for the Surron Ultra Bee. Magura MT5 levers + calipers, massive stopping power over stock. Drop-in fit.",why_popular:"#1 mod for Surron Ultra Bee owners — the stock brakes simply can't handle the speed, this is the community-approved fix",amazon_search:"Magura MT5 hydraulic brake kit Surron Ultra Bee",ebay_search:"Surron Ultra Bee hydraulic brake upgrade Magura",compatibility:"Surron Ultra Bee, Light Bee X, Storm Bee",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/FullSizeRender_f0fec78d-3820-4ccc-8632-a39c985133ed.jpg?v=1768861600",amazon_direct:"https://www.amazon.com/dp/B01EQS1Z6O",ebay_direct:"https://www.ebay.com/itm/405222388257"},
  {id:"brake-surron-tektro",title:"Tektro HD-E350 Ebike Brake Upgrade",brand:"Tektro",category:"brakes",trending:9,retail_price:140,found_price:79,description:"Purpose-built 4-piston hydraulic brakes with motor inhibitor. Best budget upgrade for Surron and light electric bikes.",why_popular:"Most affordable proper brake upgrade for Surron riders — motor cutoff built-in, night and day vs stock",amazon_search:"Tektro HD-E350 hydraulic brake ebike Surron",ebay_search:"Tektro HD-E350 hydraulic brake Surron",compatibility:"Surron, Talaria, Segway X160/X260, universal IS mount",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/FullSizeRender_dd7d47e7-7bc3-491b-9eb0-281f657044ef.jpg?v=1767367428",amazon_direct:"https://www.amazon.com/dp/B0C6XWL6N6",ebay_direct:"https://www.ebay.com/itm/354517587664"},

  // ── BATTERIES ──────────────────────────────────────────────────
  {id:"bat-luna-wolf",title:"Luna Cycle Wolf V3 52V Battery",brand:"Luna Cycle",category:"battery",trending:10,retail_price:599,found_price:449,description:"High-drain 52V 17.5Ah triangle frame pack. Built for performance builds. Best US-made battery.",why_popular:"#1 US ebike battery brand — insane range, quality Samsung/LG cells, real warranty",amazon_search:"Luna Cycle 52V battery ebike",ebay_search:"Luna Wolf 52V 17.5Ah ebike battery",compatibility:"Bafang BBS02B, BBSHD, mid-drive builds",amazon_direct:"https://lunacycle.com/luna-wolf-battery/",ebay_direct:"https://www.ebay.com/itm/147048889595"},
  {id:"bat-em3ev",title:"EM3ev 52V 17.5Ah Shark Pack",brand:"EM3ev",category:"battery",trending:9,retail_price:420,found_price:299,description:"Internationally trusted battery maker. High-quality Samsung 35E cells, downtube or triangle mount.",why_popular:"Trusted by the community for years — reliable cells, smart BMS",amazon_search:"EM3ev 52V shark battery ebike",ebay_search:"52V 17.5Ah shark battery Samsung cells",compatibility:"Universal downtube mount",amazon_direct:"https://em3ev.com/shop/battery-packs/",ebay_direct:"https://www.ebay.com/itm/277062112126"},
  {id:"bat-grin-satiator",title:"Grin Technologies Satiator Charger",brand:"Grin Technologies",category:"battery",trending:9,retail_price:185,found_price:135,description:"The world's best ebike charger. Programmable charge rate and voltage, extends battery life dramatically.",why_popular:"Every serious ebikers buys this — charges to 80% for daily use, extends battery life 2x",amazon_search:"Grin Technologies Satiator charger ebike",ebay_search:"Grin Satiator ebike charger",compatibility:"Universal 36V-72V",amazon_direct:"https://www.ebikes.ca/shop/electric-bicycle-parts/chargers/satiator.html",ebay_direct:"https://www.ebay.com/itm/203274343452"},

  // ── TITANIUM / HARDWARE ────────────────────────────────────────
  {id:"ti-bolt-wanyifa",title:"Wanyifa Full Titanium Bolt Kit",brand:"Wanyifa",category:"hardware",trending:10,retail_price:120,found_price:55,description:"Full frame titanium bolt replacement kit. Saves 150-300g, corrosion-proof, looks incredible. Available per-bike.",why_popular:"The #1 weight saving mod — looks amazing, saves real weight, lasts forever vs steel bolts",amazon_search:"Wanyifa titanium bolt kit ebike",ebay_search:"Wanyifa titanium bolt set bicycle",compatibility:"Universal M4/M5/M6 threads",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_3252.jpg?v=1763331120",amazon_direct:"https://www.amazon.com/dp/B01B50EURM",ebay_direct:"https://www.ebay.com/itm/257052970091"},
  {id:"ti-bolt-ti22",title:"Ti22 Titanium Stem & Handlebar Bolts",brand:"Ti22",category:"hardware",trending:9,retail_price:45,found_price:22,description:"Titanium stem face plate and bar bolts. Most visible hardware upgrade — zero corrosion, lightweight.",why_popular:"Easy, affordable first titanium upgrade — immediately visible and saves weight",amazon_search:"Ti22 titanium stem bolts M5",ebay_search:"titanium stem bolts M5 bicycle",compatibility:"Universal M5",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_1658.jpg?v=1765385432",amazon_direct:"https://www.amazon.com/dp/B07R8KQ2ML",ebay_direct:"https://www.ebay.com/itm/306715250066"},
  {id:"ti-brake-bolts",title:"Titanium Brake Caliper Bolts Set",brand:"Wanyifa",category:"hardware",trending:8,retail_price:35,found_price:12,description:"Titanium M6 bolts for brake caliper mounting. Saves weight where you brake — zero corrosion, looks premium.",why_popular:"Riders bolt these on with new brakes — looks amazing and weighs nothing",amazon_search:"Wanyifa titanium brake caliper bolt M6",ebay_search:"titanium brake caliper bolts M6 bicycle",compatibility:"M6x1.0 thread, standard caliper mount",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_1608.jpg?v=1763677743",amazon_direct:"https://www.amazon.com/dp/B01B50EURM"},
  {id:"ti-colored-bolts-red",title:"Colored Titanium Bolt Kit — Red",brand:"Wanyifa",category:"hardware",trending:10,retail_price:85,found_price:38,description:"Anodized red titanium bolt set for full bike dress-up. Grade 5 Ti, M4/M5/M6 assortment. Saves 150g+ and looks incredible.",why_popular:"Huge trend on Surron and Talaria builds — red bolts throughout the frame look insane in photos",amazon_search:"colored titanium bolt kit red anodized bicycle ebike",ebay_search:"colored titanium bolt set red ebike bicycle M5",compatibility:"Universal M4/M5/M6",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_3292.jpg?v=1763332131",amazon_direct:"https://www.amazon.com/dp/B019A1TDBG",ebay_direct:"https://www.ebay.com/itm/127405909329"},
  {id:"ti-colored-bolts-blue",title:"Colored Titanium Bolt Kit — Blue",brand:"Wanyifa",category:"hardware",trending:10,retail_price:85,found_price:38,description:"Anodized blue titanium bolt set. Same grade 5 Ti as the naturals but blue anodized for a custom look. Full assortment.",why_popular:"Blue and black builds everywhere — swapping to blue Ti bolts is the easiest way to get a custom look",amazon_search:"colored titanium bolt kit blue anodized bicycle ebike",ebay_search:"colored titanium bolt set blue ebike bicycle",compatibility:"Universal M4/M5/M6",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/7657B011-9AE5-4E02-BD98-B8B7674D5F4F.webp?v=1767366027",amazon_direct:"https://www.amazon.com/dp/B019A1TDBG",ebay_direct:"https://www.ebay.com/itm/127405909329"},
  {id:"ti-colored-bolts-gold",title:"Colored Titanium Bolt Kit — Gold",brand:"Wanyifa",category:"hardware",trending:9,retail_price:85,found_price:38,description:"Anodized gold/champagne titanium bolt set. The most premium looking colorway — pairs perfectly with black frames.",why_popular:"Gold on black is the premium look — huge on Surron Ultra Bee builds right now",amazon_search:"gold titanium bolt kit anodized ebike bicycle",ebay_search:"gold titanium bolt set anodized bicycle ebike",compatibility:"Universal M4/M5/M6",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-1464.jpg?v=1766779517",amazon_direct:"https://www.amazon.com/dp/B019A1TDAM",ebay_direct:"https://www.ebay.com/itm/395499606261"},

  // ── SUPERMOTO & DIRT TIRES ──────────────────────────────────────
  {id:"tire-supermoto-cst",title:"CST Supermoto Tire 20x4.0 Fat",brand:"CST",category:"tires",trending:10,retail_price:95,found_price:52,description:"Supermoto-style slick tread pattern for fat tire ebikes. Incredible road grip, head-turning look, way faster rolling than knobbies.",why_popular:"The coolest looking tire mod — supermoto vibes on your fat ebike, dramatically faster on pavement",amazon_search:"CST supermoto fat tire 20x4.0 ebike",ebay_search:"CST supermoto tire 20x4 fat ebike",compatibility:"20x4.0\" fat tire rims (Surron, RadRover, Lectric XP)",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/DC59C325-7D73-44EE-B1C1-B753BA835E0D.jpg?v=1768243678",amazon_direct:"https://www.amazon.com/dp/B0CPT4PW6V",ebay_direct:"https://www.ebay.com/itm/177895999654"},
  {id:"tire-supermoto-kenda",title:"Kenda Kraze Supermoto 20x4.0",brand:"Kenda",category:"tires",trending:9,retail_price:85,found_price:48,description:"Semi-slick supermoto pattern, high-grip rubber compound. Low rolling resistance with traction when you need it.",why_popular:"Community favourite supermoto tire — Kenda quality, perfect street/trail balance for fat bikes",amazon_search:"Kenda Kraze 20x4 fat tire supermoto ebike",ebay_search:"Kenda supermoto 20x4 fat tire ebike",compatibility:"20x4.0\" fat tire rims",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_2510.webp?v=1768243704",amazon_direct:"https://www.amazon.com/dp/B0BPD4SCHV",ebay_direct:"https://www.ebay.com/itm/405933245567"},
  {id:"tire-dirtbike-kenda",title:"Kenda Havok Pro Dirt Tire 20x4.0",brand:"Kenda",category:"tires",trending:9,retail_price:90,found_price:55,description:"Aggressive knobby dirt tire with centre ridge for straight-line speed. Rips through mud, sand and gravel.",why_popular:"Best off-road dirt tire for light electric bikes — community go-to for Surron and Talaria trail riding",amazon_search:"Kenda Havok Pro 20x4 dirt tire ebike fat",ebay_search:"Kenda Havok 20x4 fat dirt tire ebike",compatibility:"20x4.0\" fat tire rims",amazon_direct:"https://www.amazon.com/s?k=Kenda+Havok+Pro+20x4+fat+tire",ebay_direct:"https://www.ebay.com/itm/286672323396"},
  {id:"tire-dirtbike-vee-rubber",title:"Vee Tire Flow Snap Dirt Tire 20x4.0",brand:"Vee Tire",category:"tires",trending:8,retail_price:80,found_price:49,description:"Aggressive intermediate knobby. Perfect for dirt, gravel and mixed terrain. Folding bead, light weight.",why_popular:"Best light dirt tire — knobby enough for serious off-road but not too draggy on street",amazon_search:"Vee Tire Flow Snap 20x4 fat tire dirt",ebay_search:"Vee Tire Flow Snap 20x4 fat dirt ebike",compatibility:"20x4.0\" fat tire rims",amazon_direct:"https://www.amazon.com/s?k=Vee+Tire+Flow+Snap+20x4+fat+tire",ebay_direct:"https://www.ebay.com/itm/256103681113"},

  // ── BAJA LIGHTS / AUXILIARY LIGHTING ───────────────────────────
  {id:"light-baja-s2",title:"Baja Designs S2 Sport LED Pod",brand:"Baja Designs",category:"lighting",trending:10,retail_price:215,found_price:148,description:"4500 lumen LED pod light. Used by off-road racers worldwide. Waterproof, shockproof, incredibly bright wide beam.",why_popular:"The real deal off-road light — Baja Designs is the brand the pro racers use, transforms night trail riding",amazon_search:"Baja Designs S2 Sport LED light ebike",ebay_search:"Baja Designs S2 Sport LED pod light",compatibility:"Universal bar/frame mount, 12V-24V input",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-8869.jpg?v=1766847940",amazon_direct:"https://www.amazon.com/dp/B073V75WYJ",ebay_direct:"https://www.ebay.com/itm/225927658960"},
  {id:"light-baja-squadron",title:"Baja Designs Squadron Sport LED Bar",brand:"Baja Designs",category:"lighting",trending:9,retail_price:380,found_price:265,description:"Wide LED light bar, 7400 lumens. Dominator-level brightness. Makes your Surron/Talaria look like a full dirt bike.",why_popular:"The ultimate light bar — nothing else comes close for night trail sessions, looks absolutely insane",amazon_search:"Baja Designs Squadron Sport LED bar offroad ebike",ebay_search:"Baja Designs Squadron Sport LED light bar",compatibility:"Universal frame mount bracket included",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-2906.png?v=1769911475",amazon_direct:"https://www.amazon.com/dp/B01B7MZK0E",ebay_direct:"https://www.ebay.com/itm/304423607590"},
  {id:"light-auxbeam-pod",title:"Auxbeam F-16 Series LED Pods 2-Pack",brand:"Auxbeam",category:"lighting",trending:8,retail_price:65,found_price:28,description:"Budget Baja-style LED pods, 2000 lumens each. Waterproof IP68, flood+spot combo. Best value aux lights.",why_popular:"Budget pick for the Baja light look — incredible brightness per dollar, IP68 waterproof",amazon_search:"Auxbeam F-16 LED pod lights 2 pack ebike offroad",ebay_search:"Auxbeam LED pod lights 2000 lumen 2 pack",compatibility:"Universal, 12V-24V",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-4245.jpg?v=1767208703",amazon_direct:"https://www.amazon.com/dp/B08N68P68G"},

  // ── GUTS RACING ─────────────────────────────────────────────────
  {id:"seat-guts-foam",title:"Guts Racing Seat Foam & Cover Kit",brand:"Guts Racing",category:"comfort",trending:10,retail_price:120,found_price:75,description:"The #1 aftermarket seat for Surron, Talaria and light electric bikes. Thicker foam, durable gripper cover, direct fit to OEM seat pan. Night and day vs stock.",why_popular:"Every Surron Ultra Bee owner eventually buys this — stock seat is paper thin, Guts Racing is what the pros run",amazon_search:"Guts Racing seat foam cover Surron light electric bike",ebay_search:"Guts Racing seat foam Surron Ultra Bee",compatibility:"Surron Ultra Bee, Light Bee X, Talaria Sting, Segway X260",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/7AEBEE23-C9F5-4753-A3C5-5F37050138A3.jpg?v=1768243708",amazon_direct:"https://www.gutsracing.com/collections/surron"},
  {id:"seat-guts-tall",title:"Guts Racing Tall Foam Seat Kit",brand:"Guts Racing",category:"comfort",trending:9,retail_price:110,found_price:68,description:"Taller Guts Racing foam for bigger riders or more aggressive stance. Adds 1.5in of height, same bulletproof cover material. Uses OEM seat pan.",why_popular:"Taller riders love this — way more control and comfort over stock, looks factory",amazon_search:"Guts Racing tall seat foam light electric bike",ebay_search:"Guts Racing tall foam Surron seat",compatibility:"Surron Ultra Bee, Surron Light Bee X, Talaria Sting",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-7096.jpg?v=1767022845",amazon_direct:"https://www.gutsracing.com/collections/surron"},

  // ── ACCESSORIES ────────────────────────────────────────────────
  {id:"license-plate-front",title:"Universal Front License Plate Bracket",brand:"Rizoma",category:"accessories",trending:9,retail_price:45,found_price:18,description:"Adjustable front fender license plate holder. Mounts to forks or handlebars, fits standard plates. Used on Surron, Talaria, and converted ebikes.",why_popular:"Required for road-legal builds and popular for the moto look — fender or handlebar mount options",amazon_search:"front license plate bracket mount ebike moto universal",ebay_search:"front license plate holder bracket ebike motocross",compatibility:"Universal fork/handlebar mount",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-8252.jpg?v=1767021946",amazon_direct:"https://www.amazon.com/s?k=front+license+plate+bracket+motorcycle+ebike+universal"},

  // ── HANDLEBARS ─────────────────────────────────────────────────
  {id:"bar-fatbar-renthal",title:"Renthal Fatbar 28.6mm Handlebar",brand:"Renthal",category:"accessories",trending:9,retail_price:95,found_price:58,description:"The most popular handlebar upgrade for light electric bikes. 28.6mm clamp, multiple bends available, used by pro enduro and MX riders. Aluminum alloy, strong and light.",why_popular:"#1 handlebar upgrade for Surron and Talaria riders — way stronger than stock, looks like a real dirt bike",amazon_search:"Renthal Fatbar handlebar 28.6 enduro ebike",ebay_search:"Renthal Fatbar 28.6 handlebar motocross ebike",compatibility:"Surron Ultra Bee, Light Bee X, Talaria Sting, any 28.6mm stem clamp",amazon_direct:"https://www.amazon.com/dp/B003Y8M7OC"},
  {id:"bar-pro-taper",title:"Pro Taper Handlebars CR High Bend",brand:"Pro Taper",category:"accessories",trending:8,retail_price:85,found_price:52,description:"American-made CR high bend MX bars. Multiple bend options, 28.6mm tapered, the real deal MX handlebar.",why_popular:"Community favourite for light electric bikes wanting the MX look — bulletproof, feels amazing",amazon_search:"Pro Taper CR high handlebar 28.6 motocross ebike",ebay_search:"Pro Taper CR high bend handlebar 28.6",compatibility:"Surron Ultra Bee, Talaria, any 28.6mm bar clamp",amazon_direct:"https://www.amazon.com/dp/B089NDJ4DJ"},
];

export const TRENDING = [...MODS].sort((a, b) => (b.trending || 0) - (a.trending || 0));

export const CATEGORIES = [...new Set(MODS.map(m => m.category))].sort();

export function searchMods(query) {
  const q = (query || '').toLowerCase().trim();
  if (!q) return TRENDING.slice(0, 20);
  const results = [];
  for (const mod of MODS) {
    let score = 0;
    const searchable = `${mod.title} ${mod.brand} ${mod.category} ${mod.description} ${mod.why_popular || ''}`.toLowerCase();
    if (searchable.includes(q)) score += 10;
    for (const word of q.split(' ')) {
      if (word && searchable.includes(word)) score += 3;
    }
    if (score > 0) results.push([score + (mod.trending || 0), mod]);
  }
  results.sort((a, b) => b[0] - a[0]);
  return results.map(([, m]) => m);
}
