// Curated mods — photos from Timoto Bolts, source links to suppliers/manufacturers

export const MODS = [

  // ── BRAKES ─────────────────────────────────────────────────────
  {id:"brake-ultrabee-kit",title:"Ultra Bee Rear Brake Kit",brand:"Timoto Bolts",category:"brakes",trending:10,retail_price:420,found_price:375,description:"Complete rear brake kit for the Surron Ultra Bee. Everything you need for a proper brake upgrade.",why_popular:"The go-to brake upgrade for Ultra Bee owners — plug-and-play with zero guesswork",compatibility:"Surron Ultra Bee",image_url:"https://timotobolts.com/cdn/shop/files/FullSizeRender_f0fec78d-3820-4ccc-8632-a39c985133ed.jpg?v=1768861600",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=surron+ultra+bee+rear+brake+kit"},
  {id:"brake-footbrake-v2",title:"Surron Ultra Bee Footbrake Kit V2",brand:"Timoto Bolts",category:"brakes",trending:9,retail_price:420,found_price:379,description:"V2 footbrake kit for Surron Ultra Bee. Full rear foot-operated brake system — real dirt bike feel.",why_popular:"Riders who want the full moto feel upgrade to this — foot brake transforms how the bike rides",compatibility:"Surron Ultra Bee",image_url:"https://timotobolts.com/cdn/shop/files/surron-ultra-bee-foot-brake-kit-silver_938dee72-e4da-48fe-a07d-5e2a980ed850.webp?v=1767366044",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=surron+ultra+bee+foot+brake+kit"},
  {id:"ti-formula-handbrake",title:"Formula Titanium Handbrake Bolts",brand:"Timoto Bolts",category:"brakes",trending:8,retail_price:12,found_price:8,description:"Titanium replacement bolts for Formula handbrakes. Grade 5 Ti — saves weight, zero rust, looks clean.",why_popular:"Essential upgrade when running Formula brakes — titanium for almost nothing, huge improvement",compatibility:"Formula brakes",image_url:"https://timotobolts.com/cdn/shop/files/FullSizeRender_dd7d47e7-7bc3-491b-9eb0-281f657044ef.jpg?v=1767367428",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+handbrake+lever+bolts+m5+formula"},

  // ── BATTERIES ──────────────────────────────────────────────────
  {id:"bat-chi-52v",title:"Chi Battery Sur-Ron High Voltage Pack",brand:"Chi Battery Systems",category:"battery",trending:10,retail_price:2800,found_price:2350,description:"Chi Battery's high-voltage Sur-Ron battery packs. Plug-and-play upgrade for the Sur-Ron X — real warranty, cell-level fusing, assembled in Illinois.",why_popular:"Chi Battery is the most trusted name in Sur-Ron performance batteries — top-grade cells and they actually stand behind their product",compatibility:"Sur-Ron Light Bee X",amazon_direct:"https://chibatterysystems.com/collections/sur-ron"},
  {id:"bat-luna-direwolf",title:"Luna DireWolf 52V Battery",brand:"Luna Cycle",category:"battery",trending:9,retail_price:599,found_price:549,description:"Luna Cycle's 52V DireWolf triangle pack. High-drain cells, triangle frame fit, best US-made option for 52V builds.",why_popular:"Luna is the #1 US ebike battery brand — insane range, quality cells, real warranty",compatibility:"Bafang BBS02B, BBSHD, mid-drive builds",amazon_direct:"https://lunacycle.com/52v-luna-direwolf-ebike-battery/"},
  {id:"bat-grin-satiator",title:"Grin Technologies Satiator Charger",brand:"Grin Technologies",category:"battery",trending:9,retail_price:342,found_price:300,description:"The world's best ebike charger. Programmable charge rate and voltage, extends battery life dramatically.",why_popular:"Every serious ebikers buys this — charges to 80% for daily use, extends battery life 2x",compatibility:"Universal 36V-72V",amazon_direct:"https://www.amazon.com/Grin-Technologies-Cycle-Satiator-Programmable/dp/B0FLYNYC6N"},

  // ── TITANIUM / HARDWARE ────────────────────────────────────────
  {id:"ti-full-kit",title:"Full Titanium Chassis Kit — Surron Light Bee",brand:"Warp9",category:"hardware",trending:10,retail_price:379,found_price:239,description:"Complete titanium chassis bolt kit for Surron Light Bee. Every bolt upgraded to Grade 5 titanium — massive weight savings, zero rust, looks insane.",why_popular:"The ultimate full upgrade — get every bolt on your bike in titanium at once, from a trusted US brand",compatibility:"Surron Light Bee X/S",image_url:"https://timotobolts.com/cdn/shop/files/IMG_3252.jpg?v=1763331120",amazon_direct:"https://parts.electriccyclerider.com/products/warp-9-titanium-chassis-kit"},
  {id:"ti-bolt-throttle",title:"Titanium Bolts For Throttle",brand:"Timoto Bolts",category:"hardware",trending:8,retail_price:12,found_price:8,description:"Titanium replacement bolts for throttle mounting. Grade 5 Ti — corrosion-proof, lightweight, looks clean.",why_popular:"Easy upgrade when installing aftermarket throttle — clean look and never rusts",compatibility:"Universal throttle mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG_3302.jpg?v=1764710190",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+m5+clamp+bolts+ebike+throttle"},
  {id:"ti-bolt-peg",title:"Titanium Bolts For Foot Rest/Pegs",brand:"Timoto Bolts",category:"hardware",trending:8,retail_price:30,found_price:23,description:"Titanium bolts for peg and footrest mounting. Handles riding stress, zero corrosion, lightweight.",why_popular:"Pegs take a beating — titanium bolts here are essential to avoid seizing or rust",compatibility:"Universal peg mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG_3992.jpg?v=1765378234",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+footpeg+bolts+m6+electric+dirt+bike"},
  {id:"ti-bolt-direct-mount",title:"Titanium Bolts For Direct Mount — 8pc",brand:"Timoto Bolts",category:"hardware",trending:9,retail_price:40,found_price:31,description:"8-piece titanium bolt set for direct mount components. Grade 5 Ti, precision machined, saves real weight.",why_popular:"Direct mount needs titanium — these are the exact bolts that builders use on show builds",compatibility:"Direct mount compatible",image_url:"https://timotobolts.com/cdn/shop/files/1A3BB1DA-5D3B-4D85-BB04-E49BDA044DB2.jpg?v=1764709387",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+direct+mount+bolts+bicycle+m5+m6"},
  {id:"ti-bolt-key",title:"Titanium Bolts For Key Ignition",brand:"Timoto Bolts",category:"hardware",trending:7,retail_price:12,found_price:8,description:"Titanium bolts for key ignition mounting. Small detail, big impact — corrosion-proof and looks premium.",why_popular:"One of those small details that make a build stand out — titanium ignition bolts cost almost nothing",compatibility:"Surron, Talaria and most light electric bikes",image_url:"https://timotobolts.com/cdn/shop/files/29D609B4-40D1-4183-8E29-A2288057B5EB.jpg?v=1764709660",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+m4+m5+ignition+switch+bolts+electric+bike"},
  {id:"ti-bolt-fork-guards",title:"Titanium Bolts For Front Fork Guards",brand:"Timoto Bolts",category:"hardware",trending:8,retail_price:28,found_price:23,description:"Titanium bolts specifically for front fork guard mounting. Grade 5 Ti — zero corrosion, lightweight.",why_popular:"Fork guard bolts rust fast from mud and water — titanium here is a must for trail riders",compatibility:"Surron, Talaria fork guard mounts",image_url:"https://timotobolts.com/cdn/shop/files/IMG_1585_38850bc7-5229-435d-ae00-a1fd5e5d44d7.jpg?v=1764710310",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+fork+guard+bolts+m5+electric+dirt+bike"},
  {id:"ti-bolt-subframe",title:"Titanium Subframe Bolts",brand:"Timoto Bolts",category:"hardware",trending:8,retail_price:28,found_price:23,description:"Titanium subframe mounting bolts. Handles the high-stress subframe connection — lighter and rust-proof.",why_popular:"Subframe bolts are always the first to rust on trail bikes — titanium here is a smart long-term investment",compatibility:"Surron, Talaria subframe",image_url:"https://timotobolts.com/cdn/shop/files/IMG_3993.jpg?v=1764710277",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+subframe+bolts+m8+electric+dirt+bike"},
  {id:"ti-bolt-battery-lid",title:"Titanium Bolts For Side Battery Lid Guard",brand:"Timoto Bolts",category:"hardware",trending:7,retail_price:12,found_price:8,description:"Titanium bolts for side battery lid guard protection panels. Lightweight, corrosion-proof.",why_popular:"Easy upgrade that protects the battery lid mounting and looks premium — only $8",compatibility:"Surron, Talaria battery lid guard",image_url:"https://timotobolts.com/cdn/shop/files/65204D06-2AF9-402D-818A-01EF1E1C59C9.jpg?v=1765387934",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=titanium+m4+battery+guard+bolts+electric+bike"},
  {id:"ti-colored-bolts-red",title:"Colored Titanium Disc Brake Bolts — Red (12pc)",brand:"Wanyifa",category:"hardware",trending:10,retail_price:18,found_price:13,description:"Anodized red titanium M5x10 Torx disc brake rotor bolts. Grade 5 Ti (6Al-4V) — 12-piece set. Rust-proof, lightweight, looks clean.",why_popular:"Huge trend on Surron and Talaria builds — swap your rotor bolts to red for instant custom look",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_3292.jpg?v=1763332131",amazon_direct:"https://www.amazon.com/Wanyifa-Titanium-Bicycle-Screws-Colorful/dp/B019A1TDBG"},
  {id:"ti-colored-bolts-blue",title:"Colored Titanium Disc Brake Bolts — Blue (12pc)",brand:"Wanyifa",category:"hardware",trending:10,retail_price:18,found_price:13,description:"Anodized blue titanium M5x10 Torx disc brake rotor bolts. Same Grade 5 Ti as the naturals but blue anodized for a custom look.",why_popular:"Blue and black builds everywhere — swap your rotor bolts to blue for instant custom look",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/7657B011-9AE5-4E02-BD98-B8B7674D5F4F.webp?v=1767366027",amazon_direct:"https://www.amazon.com/Wanyifa-Titanium-Bicycle-Screws-Colorful/dp/B019A1TDBG"},
  {id:"ti-colored-bolts-gold",title:"Colored Titanium Disc Brake Bolts — Gold (12pc)",brand:"Wanyifa",category:"hardware",trending:9,retail_price:18,found_price:13,description:"Anodized gold/champagne titanium M5x10 Torx disc brake rotor bolts. The most premium looking colorway — pairs perfectly with black frames.",why_popular:"Gold on black is the premium look — huge on Surron Ultra Bee builds right now",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-1464.jpg?v=1766779517",amazon_direct:"https://www.amazon.com/Wanyifa-Titanium-Bicycle-Screws-Colorful/dp/B019A1TDAM"},

  // ── FRAME GUARDS ───────────────────────────────────────────────
  {id:"guard-ultra-bee",title:"Frame Guards — Surron Ultra Bee",brand:"Timoto Bolts",category:"accessories",trending:10,retail_price:280,found_price:249,description:"Custom-fit frame guards for the Surron Ultra Bee. Protects the frame from scratches, rocks and drops on trail.",why_popular:"Essential protection for Ultra Bee riders — keeps your frame looking new",compatibility:"Surron Ultra Bee",image_url:"https://timotobolts.com/cdn/shop/files/7AEBEE23-C9F5-4753-A3C5-5F37050138A3.jpg?v=1768243708",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=surron+ultra+bee+frame+guard+protection+kit"},
  {id:"guard-lbx",title:"Frame Guards — Surron Light Bee X",brand:"Timoto Bolts",category:"accessories",trending:10,retail_price:280,found_price:250,description:"Frame protection kit for the Surron Light Bee X. Prevents frame damage from rocks, stumps and hard landings.",why_popular:"LBX riders love these — your frame is expensive, protect it",compatibility:"Surron Light Bee X",image_url:"https://timotobolts.com/cdn/shop/files/DC59C325-7D73-44EE-B1C1-B753BA835E0D.jpg?v=1768243678",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=surron+light+bee+x+frame+guard+protection"},
  {id:"guard-mx",title:"Mx3/Mx4 Frame Guards",brand:"Timoto Bolts",category:"accessories",trending:9,retail_price:280,found_price:249,description:"Frame guard set for Mx3 and Mx4 models. Full frame coverage for serious trail riders — direct fit, no trimming.",why_popular:"MX riders need this — trail riding without frame guards is gambling with your bike",compatibility:"Mx3, Mx4",image_url:"https://timotobolts.com/cdn/shop/files/IMG_2510.webp?v=1768243704",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=mx4+electric+dirt+bike+frame+guard+protection"},

  // ── ACCESSORIES ────────────────────────────────────────────────
  {id:"peg-passenger-stunt",title:"Passenger & Stunt Peg",brand:"Timoto Bolts",category:"accessories",trending:9,retail_price:22,found_price:18,description:"Rear passenger foot peg for Sur-Ron Light Bee X / Segway X160 X260. Bolt-on mount, strong construction.",why_popular:"Easy install, great for two-up riding or showing off — folds out of the way when not in use",compatibility:"Sur-Ron Light Bee X, Segway X160/X260",image_url:"https://timotobolts.com/cdn/shop/files/IMG-7096.jpg?v=1767022845",amazon_direct:"https://www.ebay.com/itm/204214943991"},
  {id:"plate-vented-white",title:"Pre Made White Vented Plate",brand:"Timoto Bolts",category:"accessories",trending:8,retail_price:120,found_price:90,description:"Pre-made white vented license plate holder. Unique vented design for a clean moto look — ready to bolt on.",why_popular:"Riders love the vented look — unique design makes the bike look custom",compatibility:"Universal mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG-8252.jpg?v=1767021946",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=electric+bike+vented+license+plate+holder"},
  {id:"plate-vented-motocutz",title:"Vented Motocutz Plate",brand:"Timoto Bolts",category:"accessories",trending:8,retail_price:130,found_price:99,description:"Custom Motocutz vented license plate. Precision cut, available in multiple styles. The premium vented plate option.",why_popular:"Custom cut and unique — the Motocutz vented plate is what show builds run",compatibility:"Universal",image_url:"https://timotobolts.com/cdn/shop/files/7888B013-3CA0-4086-BAAD-82F22494EE0C.jpg?v=1767021963",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=electric+dirt+bike+vented+license+plate+custom"},
  {id:"motor-cover-surron",title:"Surron/Eride Motor Cover",brand:"Timoto Bolts",category:"accessories",trending:8,retail_price:90,found_price:70,description:"Custom motor cover for Surron and Eride motors. Protects the motor from dirt and debris, adds a clean custom look.",why_popular:"Motor protection that also looks great — one of a kind custom cover",compatibility:"Surron, Eride",image_url:"https://timotobolts.com/cdn/shop/files/98C13331-F44F-4155-A0B0-FF75ADB57AE2.jpg?v=1766848067",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=surron+motor+cover+protection+eride"},
  {id:"throttle-super73-surron",title:"Waterproof Half-Twist Throttle",brand:"eBikeling",category:"accessories",trending:9,retail_price:30,found_price:25,description:"Waterproof half-twist throttle with 3-pin Julet connector. Works on 24V/36V/48V systems, right-side mount, comes with grips.",why_popular:"Top-rated throttle on Amazon — waterproof, easy install, works with virtually any ebike system",compatibility:"Universal 24V-48V, Surron, Super 73, most electric bikes",image_url:"https://timotobolts.com/cdn/shop/files/IMG-7896.jpg?v=1767022794",amazon_direct:"https://www.amazon.com/EBIKELING-Waterproof-Throttle-Electric-Bicycle/dp/B0BGM539H3"},
  {id:"light-switch-surron",title:"Surron Light Switch",brand:"Timoto Bolts",category:"accessories",trending:8,retail_price:25,found_price:17,description:"Clean aftermarket light switch for Surron. Direct replacement, simple install, reliable toggle.",why_popular:"Stock light switch fails eventually — replacement is better quality and easy to install",compatibility:"Surron",image_url:"https://timotobolts.com/cdn/shop/files/DFA48335-36C5-4394-A48C-F75F38C9696B.jpg?v=1769871102",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=electric+dirt+bike+toggle+light+switch+surron"},

  // ── LIGHTING ───────────────────────────────────────────────────
  {id:"light-baja-super73-kit",title:"Super 73 Universal Baja Light Kit",brand:"Timoto Bolts",category:"lighting",trending:10,retail_price:65,found_price:46,description:"Battery-powered Baja-style light kit for Super 73. No wiring needed — plug and play. Waterproof and insanely bright.",why_popular:"Easiest Baja light install on the market — universal fit, no wiring, looks like the pro builds",compatibility:"Super 73, universal bar mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG-8869.jpg?v=1766847940",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=baja+light+kit+battery+powered+offroad+pod"},
  {id:"light-baja-super73",title:"Super 73 Baja Light",brand:"Timoto Bolts",category:"lighting",trending:9,retail_price:60,found_price:45,description:"Baja-style LED light designed for Super 73. Direct mount, massive output, weatherproof.",why_popular:"The definitive Super 73 Baja light — direct mount, no hacks, looks factory",compatibility:"Super 73",image_url:"https://timotobolts.com/cdn/shop/files/IMG-2906.png?v=1769911475",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=baja+led+light+pod+offroad+electric+bike"},
  {id:"light-rock-super73",title:"ShredLights SL-FX+ E-Bike Underglow",brand:"ShredLights",category:"lighting",trending:8,retail_price:100,found_price:90,description:"App-controlled LED underglow kit. 10,000+ color combos, magnetic mount, no wiring, 30-day guarantee. Works on Super 73 and most ebikes.",why_popular:"The rock light look is massive right now — ShredLights is the easiest plug-and-play underglow on the market",compatibility:"Super 73, universal magnetic mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG-4245.jpg?v=1767208703",amazon_direct:"https://shredlights.com/products/sl-fx-e-bike-underglow-bundle"},
  {id:"light-rock-surron-lbx",title:"ShredLights Surron LED Underglow Kit",brand:"ShredLights",category:"lighting",trending:9,retail_price:100,found_price:90,description:"Dedicated underglow kit for Surron. App-controlled, 10,000+ color combos, quick-release S-LOCK mount, no wiring, 1-year warranty.",why_popular:"Surron riders love the underglow look — ShredLights is the top-rated no-wire underglow for Surron",compatibility:"Surron Light Bee X, Surron Ultra Bee",image_url:"https://timotobolts.com/cdn/shop/files/41A64092-D439-4916-9E61-3E4EF56EC2A6.webp?v=1767491938",amazon_direct:"https://shredlights.com/products/surron-led-underglow-kit"},
  {id:"light-baja-yellow",title:"Yellow Flood Baja Light",brand:"Timoto Bolts",category:"lighting",trending:7,retail_price:40,found_price:32,description:"Yellow-tinted flood Baja light. Wide beam pattern, weatherproof — the classic rally/trail riding look.",why_popular:"Yellow flood is the off-road trail light look — riders running night sessions love these",compatibility:"Universal bar mount",image_url:"https://timotobolts.com/cdn/shop/files/FullSizeRender_b1eae354-d402-4631-a23d-eb218cdf5b42.heic?v=1767743866",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=yellow+flood+baja+light+pod+offroad+led"},
  {id:"light-baja-white",title:"White Flood Baja Light",brand:"Timoto Bolts",category:"lighting",trending:7,retail_price:40,found_price:32,description:"White flood Baja light. Pure white wide beam, waterproof housing — max visibility for night riding.",why_popular:"White flood is the cleanest Baja look — pairs perfectly with the Super 73 or any light electric bike",compatibility:"Universal bar mount",image_url:"https://timotobolts.com/cdn/shop/files/FullSizeRender_fa5cb715-f558-42c9-a5d6-f24a5ad1c494.heic?v=1767743568",amazon_direct:"https://www.aliexpress.com/wholesale?SearchText=white+flood+led+baja+light+pod+offroad"},
];

export const TRENDING = [...MODS].sort((a, b) => (b.trending || 0) - (a.trending || 0));

export const CATEGORIES = [...new Set(MODS.map(m => m.category))].sort();

export function searchMods(query) {
  const q = (query || '').toLowerCase().trim();
  if (!q) return TRENDING.slice(0, 20);
  const results = [];
  for (const mod of MODS) {
    let score = 0;
    const searchable = `${mod.title} ${mod.brand} ${mod.category} ${mod.description} ${mod.why_popular || ''}`.toLowerCase();
    if (searchable.includes(q)) score += 10;
    for (const word of q.split(' ')) {
      if (word && searchable.includes(word)) score += 3;
    }
    if (score > 0) results.push([score + (mod.trending || 0), mod]);
  }
  results.sort((a, b) => b[0] - a[0]);
  return results.map(([, m]) => m);
}
