// Curated mods — verified direct links only, prices match the linked product pages

export const MODS = [

  // ── BATTERIES ──────────────────────────────────────────────────
  {id:"bat-chi-surron",title:"Chi Battery Gladiator 72 Pulsar — Sur-Ron",brand:"Chi Battery Systems",category:"battery",trending:10,retail_price:1999,found_price:1599,description:"72V 45Ah Gladiator Pulsar battery for Sur-Ron. Cell-level fusing, laser-engraved steel enclosure, 3,240Wh. Made to order in Illinois.",why_popular:"The most trusted Sur-Ron battery upgrade — massive power, real warranty, built in the USA",compatibility:"Sur-Ron Light Bee X/S",image_url:"https://cdn.shopify.com/s/files/1/0567/0033/8356/files/72PT1E1.jpg?v=1736972195",amazon_direct:"https://chibatterysystems.com/products/72pulsar"},
  {id:"bat-grin-satiator",title:"Grin Technologies Satiator Charger",brand:"Grin Technologies",category:"battery",trending:9,retail_price:342,found_price:300,description:"The world's best programmable ebike charger. Set charge rate and voltage to charge to 80% for daily use — extends battery life dramatically.",why_popular:"Every serious ebikers buys this — charge to 80% extends battery lifespan by 2x or more",compatibility:"Universal 36V–72V",image_url:"https://timotobolts.com/cdn/shop/files/1A3BB1DA-5D3B-4D85-BB04-E49BDA044DB2.jpg?v=1764709387",amazon_direct:"https://www.amazon.com/Grin-Technologies-Cycle-Satiator-Programmable/dp/B0FLYNYC6N"},

  // ── HARDWARE ───────────────────────────────────────────────────
  {id:"ti-full-kit",title:"Full Titanium Chassis Bolt Kit — Surron Light Bee",brand:"Tarazon",category:"hardware",trending:10,retail_price:379,found_price:158,description:"Complete TC4 titanium alloy bolt kit for Surron Light Bee X / Segway X160/X260. Every chassis bolt upgraded — triple tree, subframe, motor, brakes, footpegs and more. Ships free from China.",why_popular:"The cheapest full titanium kit online — $158 vs $379 US retail. Same TC4 grade, ships free via eBay",compatibility:"Surron Light Bee X/S, Segway X160/X260",image_url:"https://timotobolts.com/cdn/shop/files/IMG_3252.jpg?v=1763331120",amazon_direct:"https://www.ebay.com/itm/206099683633"},
  {id:"ti-colored-bolts-red",title:"Colored Titanium Disc Brake Bolts — Rainbow (12pc)",brand:"Wanyifa",category:"hardware",trending:10,retail_price:18,found_price:13,description:"Rainbow/colorful anodized titanium M5x10 Torx disc brake rotor bolts. Grade 5 Ti (6Al-4V) — 12-piece set. Rust-proof, lightweight.",why_popular:"Huge trend on Surron and Talaria builds — swap your rotor bolts for instant custom look",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG_3292.jpg?v=1763332131",amazon_direct:"https://www.amazon.com/Wanyifa-Titanium-Bicycle-Screws-Colorful/dp/B019A1TDBG"},
  {id:"ti-colored-bolts-blue",title:"Colored Titanium Disc Brake Bolts — Blue (12pc)",brand:"Wanyifa",category:"hardware",trending:10,retail_price:18,found_price:13,description:"Anodized blue titanium M5x10 Torx disc brake rotor bolts. Grade 5 Ti — 12-piece set.",why_popular:"Blue and black builds everywhere — swap your rotor bolts to blue for instant custom look",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/7657B011-9AE5-4E02-BD98-B8B7674D5F4F.webp?v=1767366027",amazon_direct:"https://www.amazon.com/Wanyifa-12Pcs-Titanium-Bicycle-Screws/dp/B019A1TDA2"},
  {id:"ti-colored-bolts-gold",title:"Colored Titanium Disc Brake Bolts — Gold (12pc)",brand:"Wanyifa",category:"hardware",trending:9,retail_price:18,found_price:13,description:"Anodized gold titanium M5x10 Torx disc brake rotor bolts. Grade 5 Ti — 12-piece set. The premium colorway.",why_popular:"Gold on black is the premium look — huge on Surron Ultra Bee builds right now",compatibility:"Avid, Formula, Hayes, Magura, Shimano, SRAM disc brakes",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/IMG-1464.jpg?v=1766779517",amazon_direct:"https://www.amazon.com/Wanyifa-Titanium-Bicycle-Screws-Colorful/dp/B019A1TDAM"},

  // ── BRAKES ─────────────────────────────────────────────────────
  {id:"brake-rotor-ultra-bee",title:"270mm Floating Brake Rotor + Bracket — Sur-Ron Ultra Bee",brand:"TOFR",category:"brakes",trending:9,retail_price:90,found_price:66,description:"270mm floating front brake disc rotor with caliper bracket adapter for the Sur-Ron Ultra Bee. Two-piece floating design for better heat dissipation and consistent stopping power.",why_popular:"Upgrading to a bigger floating rotor is the #1 brake mod — more stopping power and the classic moto look",compatibility:"Sur-Ron Ultra Bee (2022–2024)",image_url:"https://i.ebayimg.com/images/g/cf0AAeSwKsNpgRJP/s-l1600.webp",amazon_direct:"https://www.amazon.com/TOFR-Floating-Bracket-Adaptor-Sur-ron/dp/B0DD73Y9GP"},
  {id:"brake-ultra-bee",title:"Hydraulic Brake Assembly — Sur-Ron Ultra Bee",brand:"Generic",category:"brakes",trending:10,retail_price:180,found_price:140,description:"Complete OEM-spec hydraulic brake assembly for the Sur-Ron Ultra Bee. Includes caliper, master cylinder, brake hose, pads, and caliper bracket. Brand new, never mounted. 1-year warranty.",why_popular:"The most popular direct-fit brake replacement for the Ultra Bee — complete assembly, bolt straight on",compatibility:"Sur-Ron Ultra Bee (2022–2024)",image_url:"https://cdn.shopify.com/s/files/1/0971/2340/2040/files/FullSizeRender_f0fec78d-3820-4ccc-8632-a39c985133ed.jpg",amazon_direct:"https://www.amazon.com/dp/B0GBWZ62LD"},

  // ── ACCESSORIES ────────────────────────────────────────────────
  {id:"throttle-surron-ebike",title:"Waterproof Half-Twist Throttle",brand:"eBikeling",category:"accessories",trending:9,retail_price:30,found_price:25,description:"Waterproof half-twist throttle with 3-pin Julet connector. Works on 24V/36V/48V systems, right-side mount, comes with grips.",why_popular:"Top-rated throttle on Amazon — waterproof, easy install, works with virtually any ebike system",compatibility:"Universal 24V–48V, Surron, Super 73, most electric bikes",image_url:"https://timotobolts.com/cdn/shop/files/IMG-7896.jpg?v=1767022794",amazon_direct:"https://www.amazon.com/EBIKELING-Waterproof-Throttle-Electric-Bicycle/dp/B0BGM539H3"},
  {id:"peg-passenger-surron",title:"Foldable Passenger Foot Pegs — Sur-Ron/Segway",brand:"JFG Racing",category:"accessories",trending:9,retail_price:80,found_price:60,description:"Bolt-on foldable rear passenger foot pegs for Sur-Ron Light Bee X/S and Segway X160/X260. CNC aluminum, folds flat when not in use.",why_popular:"Easy install, great for two-up riding — folds away cleanly when solo",compatibility:"Sur-Ron Light Bee X/S, Segway X160/X260",image_url:"https://timotobolts.com/cdn/shop/files/IMG-7096.jpg?v=1767022845",amazon_direct:"https://www.amazon.com/JFG-RACING-Surron-Bracket-Electric/dp/B0BR5J9MLH"},

  // ── LIGHTING ───────────────────────────────────────────────────
  {id:"light-baja-sport-surron-white",title:"Baja Designs S2 Sport Headlight Kit (White) — Sur-Ron/Talaria",brand:"Baja Designs",category:"lighting",trending:9,retail_price:185,found_price:185,description:"The more affordable Baja Designs S2 Sport headlight kit — plug-and-play for Sur-Ron Light Bee X and Talaria. 1,581 lumens, dual-chip driving combo lens. Includes harness, switch, bracket, and amber lens. Lifetime warranty.",why_popular:"Same Baja Designs quality and plug-and-play install as the Pro at a lower price — perfect if you want the Baja name without the Pro price tag",compatibility:"Sur-Ron Light Bee X/S, Talaria MX3/MX4/MX5, E-Ride Pro S/SS",image_url:"https://electrixmotoco.com/cdn/shop/files/3_dca45746-17bf-4b85-bf49-8f938af84b02.png?v=1759420598&width=1200",amazon_direct:"https://www.bajadesigns.com/products/s2-sport-headlight-kit-sur-ron-talaria/"},
  {id:"light-baja-sport-surron-amber",title:"Baja Designs S2 Sport Headlight Kit (Amber/Yellow) — Sur-Ron/Talaria",brand:"Baja Designs",category:"lighting",trending:9,retail_price:185,found_price:185,description:"The S2 Sport kit comes with both clear and amber lenses — swap to the included amber lens for a yellow beam that cuts through dust, fog, and rain. 1,581 lumens, plug-and-play. Same trail-proven Baja Designs quality at the Sport price.",why_popular:"The Sport with amber is the go-to budget Baja option for trail riders — same yellow beam as the Pro, costs less, still plug-and-play",compatibility:"Sur-Ron Light Bee X/S, Talaria MX3/MX4/MX5, E-Ride Pro S/SS",image_url:"https://electrixmotoco.com/cdn/shop/files/3_dca45746-17bf-4b85-bf49-8f938af84b02.png?v=1759420598&width=1200",amazon_direct:"https://www.bajadesigns.com/products/s2-sport-headlight-kit-sur-ron-talaria/"},
  {id:"light-rock-super73",title:"ShredLights SL-FX+ E-Bike Underglow Bundle",brand:"ShredLights",category:"lighting",trending:8,retail_price:100,found_price:90,description:"App-controlled LED underglow kit. 10,000+ color combos, magnetic mount, no wiring, 30-day guarantee. Works on Super 73 and most ebikes.",why_popular:"The rock light look is massive right now — ShredLights is the easiest plug-and-play underglow on the market",compatibility:"Super 73, universal magnetic mount",image_url:"https://timotobolts.com/cdn/shop/files/IMG-4245.jpg?v=1767208703",amazon_direct:"https://shredlights.com/products/sl-fx-e-bike-underglow-bundle"},
  {id:"light-rock-surron-lbx",title:"ShredLights Surron LED Underglow Kit",brand:"ShredLights",category:"lighting",trending:9,retail_price:100,found_price:90,description:"Dedicated underglow kit for Surron. App-controlled, 10,000+ color combos, quick-release S-LOCK mount, no wiring, 1-year warranty.",why_popular:"Surron riders love the underglow look — ShredLights is the top-rated no-wire underglow for Surron",compatibility:"Surron Light Bee X, Surron Ultra Bee",image_url:"https://timotobolts.com/cdn/shop/files/41A64092-D439-4916-9E61-3E4EF56EC2A6.webp?v=1767491938",amazon_direct:"https://shredlights.com/products/surron-led-underglow-kit"},

  // ── TIRES ───────────────────────────────────────────────────────
  {id:"tire-pirelli-mt60rs-21",title:"Pirelli MT60RS 90/90-21 Supermoto Front Tire",brand:"Pirelli",category:"tires",trending:10,retail_price:221,found_price:185,description:"Pirelli MT60RS dual-compound supermoto front tire, 90/90-21. Radial construction, DOT legal. The tire every serious Sur-Ron supermoto build runs.",why_popular:"The #1 supermoto tire conversion for the Light Bee X — MT60RS is what every serious build runs",compatibility:"Sur-Ron Light Bee X (supermoto conversion), Talaria, any 21\" front wheel",image_url:"https://www.revzilla.com/product_images/1459/2070/pirelli_mt60_rs_tires_300x300.jpg",amazon_direct:"https://www.ebay.com/itm/205396200466"},
  {id:"tire-michelin-ps2-17",title:"Michelin Pilot Street 2 Supermoto Tire — Sur-Ron/Talaria (17\" Wheel)",brand:"Michelin",category:"tires",trending:10,retail_price:110,found_price:100,description:"The most popular street supermoto tire for Sur-Ron and Talaria 17\" wheel conversions. Michelin Pilot Street 2 — DOT legal, silica compound, outstanding wet and dry grip. Multiple sizes for 17\" supermoto wheel builds.",why_popular:"Everyone doing a supermoto build runs the Michelin Pilot Street 2 — #1 most searched street tire for Sur-Ron, perfect pavement grip for 17\" wheel setups",compatibility:"Sur-Ron Light Bee X, Talaria (17\" supermoto wheel conversion)",image_url:"https://revrides.com/cdn/shop/files/michelin_pilot_street2_tires_750x750_ec60bd50-46cf-451d-8f6c-ff5d570e9f0f.jpg?v=1736278308",amazon_direct:"https://revrides.com/products/michelin-pilot-street-2-tire-for-surron-e-ride-pro-talaria-and-more"},

  // ── SEATS ───────────────────────────────────────────────────────
  {id:"seat-guts-surron-black",title:"Guts Racing Ribbed Seat Cover (Black) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:10,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Black. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Black is the #1 seat cover — Guts Racing is the pro brand every serious rider runs, non-slip for aggressive riding",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://parts.electriccyclerider.com/cdn/shop/files/complete-seat-hardcore-gripper-guts-racing-black-sur-ron-lb-x-segway-x260-gut-001-bk-guts-racing.png?v=1736720792",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-blue",title:"Guts Racing Ribbed Seat Cover (Blue) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:10,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). YZ Blue. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Blue is the most popular custom color — ties blue fender and bolt builds together perfectly",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://electrixmotoco.com/cdn/shop/files/GUTSBlackBlue.png",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-red",title:"Guts Racing Ribbed Seat Cover (Red) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:10,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Red. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Red builds are massive right now — Guts Racing red seat is the finishing touch on any red themed Sur-Ron",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://www.twowheelsempire.com/cdn/shop/files/guts-racing-gripper-ribbed-black-red-seat-cover-for-surron-light-bee-01-8r29s21t21-1145466476.webp?v=1741935608",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-white",title:"Guts Racing Ribbed Seat Cover (White) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:10,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). White. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"White/black builds are trending hard — the white Guts Racing cover gives the cleanest factory look",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://parts.electriccyclerider.com/cdn/shop/files/complete-seat-hardcore-gripper-guts-racing-black-white-sur-ron-lb-x-segway-x260-gut-001-wh-guts-racing.png?v=1736720787",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-yellow",title:"Guts Racing Ribbed Seat Cover (Yellow) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). RMZ Yellow. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Yellow builds turn heads — RMZ Yellow seat cover is the perfect pop of color on any dark frame",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://i.ebayimg.com/images/g/VEoAAeSw~GNofn~Q/s-l1600.jpg",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-orange",title:"Guts Racing Ribbed Seat Cover (Orange) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). KTM Orange. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"KTM Orange is the most popular accent color for Sur-Ron — instant moto look, huge on TikTok builds",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://www.twowheelsempire.com/cdn/shop/files/guts-racing-gripper-ribbed-black-orange-seat-cover-for-surron-light-bee-01-8r33s21t21-1145466478.webp?v=1741935610",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-green",title:"Guts Racing Ribbed Seat Cover (Green) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). KX Green. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"KX Green is the top choice for Kawasaki-inspired and forest builds — stands out in every trail photo",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://cdn4.volusion.store/twbgf-rqvmt/v/vspfiles/photos/27-8-SURRON-RIBBED-COVER-2.jpg",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-grey",title:"Guts Racing Ribbed Seat Cover (Grey) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Grey. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Grey is the clean neutral that works with any build color — understated pro look, very popular",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://parts.electriccyclerider.com/cdn/shop/files/complete-seat-hardcore-gripper-guts-racing-black-grey-sur-ron-lb-x-segway-x260-gut-001-gy-guts-racing.png?v=1736720787",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-purple",title:"Guts Racing Ribbed Seat Cover (Purple) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Purple. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Purple builds are blowing up — unique color that nobody else has, the most eye-catching seat on the trail",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://parts.electriccyclerider.com/cdn/shop/files/complete-seat-hardcore-gripper-guts-racing-black-purple-sur-ron-lb-x-segway-x260-gut-001-pu-guts-racing.png?v=1736720792",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-pink",title:"Guts Racing Ribbed Seat Cover (Pink) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:9,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Pink. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Pink Sur-Rons are a massive trend — the Guts Racing pink seat is the signature piece of every pink build",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://i.ebayimg.com/images/g/Nz8AAeSwJhdocXm3/s-l1600.jpg",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-surron-camo",title:"Guts Racing Ribbed Seat Cover (Camo) — Sur-Ron Light Bee",brand:"Guts Racing",category:"seats",trending:8,retail_price:80,found_price:79,description:"Official Guts Racing ribbed seat cover for Sur-Ron Light Bee X (2018–2025). Camo. Stock height, non-slip ribbed grip texture, made to order in the USA.",why_popular:"Camo builds are huge for trail and bush riding — the Guts Racing camo seat completes the tactical outdoor look",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://cdn4.volusion.store/twbgf-rqvmt/v/vspfiles/photos/27-8-SURRON-RIBBED-COVER-2.jpg",amazon_direct:"https://www.gutsracing.com/product-p/27-8-surron-ribbed-cover.htm"},
  {id:"seat-guts-outlet",title:"Guts Racing Seat Cover OUTLET — Sur-Ron Light Bee (Best Price)",brand:"Guts Racing",category:"seats",trending:10,retail_price:80,found_price:30,description:"Guts Racing Factory Outlet on eBay — overstock and returned Sur-Ron seat covers at massive discounts. Colors vary by availability. Same quality, $30 vs $80 retail. Stock height.",why_popular:"The best deal on Guts Racing seats — outlet runs $30 vs $80 retail, always has new stock appearing as old listings sell out",compatibility:"Sur-Ron Light Bee X/S (2018–2025)",image_url:"https://i.ebayimg.com/images/g/xlYAAeSwDyRocXhJ/s-l400.webp",amazon_direct:"https://www.ebay.com/sch/m.html?_ssn=gutsoutlet&_nkw=sur-ron+seat+cover&LH_BIN=1"},
  {id:"seat-foam-surron",title:"Replacement Seat Foam & Cover — Sur-Ron Light Bee",brand:"NACORE",category:"seats",trending:8,retail_price:45,found_price:32,description:"Complete drop-in seat foam replacement with carbon fiber look cover for Sur-Ron X/S. No modifications needed — direct swap for OEM seat.",why_popular:"Cheap complete seat refresh — fix a beat-up OEM seat or upgrade to carbon fiber look for under $35",compatibility:"Sur-Ron Light Bee X/S",image_url:"https://i.ebayimg.com/images/g/u1gAAeSwi~JpsTxv/s-l500.jpg",amazon_direct:"https://www.amazon.com/NACORE-Cushion-Compatible-Electric-CARBON/dp/B0C89S7FT7"},

  // ── SUSPENSION ──────────────────────────────────────────────────
  {id:"shock-dnm-surron",title:"DNM Burner 265mm Rear Shock — Sur-Ron Light Bee X",brand:"DNM",category:"suspension",trending:10,retail_price:150,found_price:89,description:"DNM Burner adjustable rear shock, 265mm eye-to-eye, 450lbs spring. Direct bolt-on for Sur-Ron Light Bee X. Adjustable preload and rebound damping.",why_popular:"The most popular Sur-Ron shock upgrade — dramatically better than stock, easy bolt-on, huge improvement for heavier riders",compatibility:"Sur-Ron Light Bee X/S",image_url:"https://i.ebayimg.com/images/g/1NMAAeSwNBxos0zV/s-l1600.jpg",amazon_direct:"https://www.amazon.com/DJ-Motor-265mm-450lbs-Burner-Electric/dp/B0BPXLNCPS"},

  // ── CONTROLS ────────────────────────────────────────────────────
  {id:"grips-odi-emig",title:"ODI Emig V2 Lock-On MX Grips",brand:"ODI",category:"controls",trending:9,retail_price:35,found_price:28,description:"ODI Emig V2 Pro lock-on grips, 110mm. No-wire clamp system, dual compound rubber. Used by top motocross and enduro pros worldwide.",why_popular:"The grip upgrade everyone does first — ODI lock-on never slips, lasts years, and looks insane on any build",compatibility:"Sur-Ron, Talaria, Segway X160/X260, universal 7/8\" (22mm) handlebars",image_url:"https://www.odigrips.com/cdn/shop/products/H36E2WH.jpg?v=1683935651",amazon_direct:"https://www.amazon.com/ODI-Emig-V2-Lock-Grips/dp/B081QTY58M"},

  // ── GUARDS ──────────────────────────────────────────────────────
  {id:"guards-geo-emoto",title:"GEO E-Moto Handguards — Sur-Ron/Talaria/Beta",brand:"GEO",category:"guards",trending:9,retail_price:60,found_price:45,description:"Purpose-built handguards for Sur-Ron, Talaria and Beta electric dirt bikes. Aerospace-grade polyethylene, fits 7/8\" and 1-1/8\" bars. Built-in brake reservoir clearance.",why_popular:"Designed specifically for e-moto — not repurposed MX guards. Fits perfectly with no modifications needed",compatibility:"Sur-Ron Light Bee X/S, Talaria Sting, Beta electric dirt bikes",image_url:"https://revrides.com/cdn/shop/files/S-HGUARD-2-WITH-STICKERS-scaled_grande.jpg?v=1727302267",amazon_direct:"https://www.amazon.com/Moto-Handguards-Talaria-electic-handguards/dp/B0CPVSF9Y7"},
  {id:"plate-nicecnc-surron",title:"CNC Aluminum License Plate Holder — Sur-Ron Light Bee",brand:"NICECNC",category:"guards",trending:8,retail_price:30,found_price:22,description:"CNC aluminum tail light and license plate holder bracket for Sur-Ron Light Bee X/S/L1E and Segway X160/X277. Clean OEM look, all hardware included.",why_popular:"Cleanest plate mount available — NICECNC quality, installs in minutes, makes the back end look finished",compatibility:"Sur-Ron Light Bee X/S/L1E, Segway X160/X277",image_url:"https://www.nicecnc.com/cdn/shop/files/1221188515_6.jpg?v=1718787921&width=1024",amazon_direct:"https://www.amazon.com/NICECNC-Licence-Mounting-Bracket-Compatible/dp/B0DSG1H8NB"},
  {id:"front-number-plate-surron",title:"Front Number Plate — Sur-Ron Light Bee X (JFG Racing)",brand:"JFG Racing",category:"guards",trending:9,retail_price:25,found_price:18,description:"Bolt-on front number plate / front fender plate for Sur-Ron Light Bee X. Lightweight plastic, moto-style look. Instantly transforms the front end to look like a real dirt bike.",why_popular:"The #1 visual mod after seat and grips — the front number plate makes the Sur-Ron look like a full moto, huge trend right now",compatibility:"Sur-Ron Light Bee X/S",image_url:"https://jfgmotor.com/cdn/shop/files/front-number-plate-for-sur-ron-jfg-racing-1.jpg?v=1750480820",amazon_direct:"https://www.amazon.com/dp/B09KPNTBRP"},
  {id:"front-number-plate-nicecnc-carbon",title:"Carbon Fiber Front Number Plate — Sur-Ron Light Bee X (NICECNC)",brand:"NICECNC",category:"guards",trending:9,retail_price:30,found_price:22,description:"Real carbon fiber front number plate for Sur-Ron Light Bee X/S and Segway X160/X260. Ultralight, won't crack in moisture or UV. Direct bolt-on, ships from US warehouse.",why_popular:"Carbon fiber plate is the premium upgrade — lighter than plastic, looks insane, NICECNC quality that riders trust",compatibility:"Sur-Ron Light Bee X/S, Segway X160/X260",image_url:"https://m.media-amazon.com/images/I/711Ktvivg+L._AC_SL1500_.jpg",amazon_direct:"https://www.amazon.com/dp/B0DTHV6WBH"},
  {id:"front-number-plate-urlwall",title:"Universal Front Number Plate — Sur-Ron/Talaria/Segway (URLWALL)",brand:"URLWALL",category:"guards",trending:8,retail_price:25,found_price:18,description:"Premium ABS front number plate with 35cm adjustable mounting straps. Fits Sur-Ron, Talaria, Segway X160/X260, Rawrr Mantis, E-Ride Pro and more. Tool-free strap adjustment.",why_popular:"Most universal front plate available — fits almost every electric dirt bike, tons of 5-star reviews, cheapest way to get the moto look",compatibility:"Sur-Ron, Talaria, Segway X160/X260, E-Ride Pro, Rawrr Mantis, universal",image_url:"https://m.media-amazon.com/images/I/61Zl70cAvAL._AC_SL1200_.jpg",amazon_direct:"https://www.amazon.com/dp/B0C1GP8W6W"},
  {id:"front-number-plate-odi",title:"ODI DH Front Number Plate — Sur-Ron/Talaria/Segway",brand:"ODI",category:"guards",trending:10,retail_price:26,found_price:26,description:"The ODI Signature Downhill Number Plate — the most popular front plate upgrade in the Sur-Ron community. Wide, shield-shaped, covers the front wiring. Designed by 5x UCI DH World Cup Champion Aaron Gwin. Available in Black, Grey, Blue, Red, and Orange.",why_popular:"ODI is the most trusted name in MX grips — their front plate is the #1 go-to for Sur-Ron and e-moto builds, pairs perfectly with ODI Emig grips",compatibility:"Sur-Ron Light Bee X/S, Talaria, Segway X160/X260, any dual-crown fork bike",image_url:"https://www.odigrips.com/cdn/shop/products/DHPlate_NoDecal_Black.jpg?v=1674779069",amazon_direct:"https://www.odigrips.com/products/odi-dh-number-plate"},

  // ── GRAPHICS ────────────────────────────────────────────────────
{id:"graphics-kungfu-plate-sticker",title:"Kungfu Graphics Front Number Plate Sticker — Sur-Ron Light Bee X",brand:"Kungfu Graphics",category:"graphics",trending:9,retail_price:40,found_price:30,description:"Front number plate graphic decal only for Sur-Ron Light Bee X (2017–2024). Same 3M vinyl and overlaminate as the full kit. Add your rider name and number free at checkout. Perfect if you only want to bling the front plate.",why_popular:"Most popular front-plate-only sticker — gets the full moto look on just the front plate, way cheaper than the full kit",compatibility:"Sur-Ron Light Bee X/S (2017–2024)",image_url:"https://m.media-amazon.com/images/I/71uH91RTvbL._AC_SL1500_.jpg",amazon_direct:"https://www.amazon.com/Kungfu-Graphics-Sur-Ron-2017-2024-SRX17N088-KO/dp/B0DNQK3BY2"},
  {id:"graphics-plate-decal-combo",title:"Front Number Plate + Custom Decal Combo — Sur-Ron/Talaria (20+ Colors)",brand:"Generic",category:"graphics",trending:10,retail_price:45,found_price:35,description:"Buy the physical front number plate AND custom graphics decal together in one kit — guaranteed to fit perfectly. 20+ color combos, 8 font choices, add your rider name and number. Works on Sur-Ron Light Bee X/S, Talaria, Segway X260, Super73, E-Ride Pro. Premium UV-resistant vinyl.",why_popular:"Best value for getting the plate AND matching sticker together — no sizing guesswork, everything fits perfectly, over 20 colors to choose from",compatibility:"Sur-Ron Light Bee X/S, Talaria Sting MX3/R MX4, Segway X260/X160, Super73, E-Ride Pro",image_url:"https://dirtsurfers.co/cdn/shop/files/Design_your_own_Light_bee.png?v=1761317450",amazon_direct:"https://www.amazon.com/dp/B0DQXV67P4"},
  {id:"graphics-dirtsurfers-plate-decal",title:"Design-Your-Own Front Plate Decal — Sur-Ron Light Bee X (Dirt Surfers)",brand:"Dirt Surfers",category:"graphics",trending:9,retail_price:36,found_price:20,description:"Fully custom front number plate sticker for Sur-Ron Light Bee X — design it exactly how you want online. 6.0 mil high-tack vinyl base + 10.0 mil overlaminate. Scratch, UV, and impact resistant. Gloss, matte, metallic, or chrome sparkle finish options. 3–4 day production, tracked shipping.",why_popular:"The most customizable plate sticker available — build your own design online, pick any color and finish, comes out looking fully custom",compatibility:"Sur-Ron Light Bee X (ODI-style number plate)",image_url:"https://dirtsurfers.co/cdn/shop/files/Design_your_own_Light_bee.png?v=1761317450",amazon_direct:"https://dirtsurfers.co/products/copy-of-surron-odi-numberplate-decal"},
  {id:"graphics-motocutz-plate-decal",title:"Custom ODI Front Number Plate Sticker — Sur-Ron (MotocutzMX)",brand:"MotocutzMX",category:"graphics",trending:9,retail_price:56,found_price:26,description:"Fully custom ODI-style front number plate sticker for Sur-Ron. 21mil high-tack vinyl with air release tech. Options: gloss, matte, metallic, holographic, chrome. Add your name and number. Fast 24/7 customer service, free shipping.",why_popular:"Top pick for holographic and chrome plate stickers — no other brand offers holographic finish for the Sur-Ron front plate, makes it look insane",compatibility:"Sur-Ron Light Bee X/S (ODI-style number plate)",image_url:"https://motocutzmx.com/cdn/shop/files/Screenshot2025-01-02at6.32.54PM.png?v=1735871581",amazon_direct:"https://motocutzmx.com/products/surron-number-plate-decal-custom"},
  {id:"graphics-effex-evo-kit",title:"Factory Effex EVO Graphic Kit — Sur-Ron Light Bee",brand:"Factory Effex",category:"graphics",trending:9,retail_price:125,found_price:125,description:"Factory Effex EVO full graphics kit for Sur-Ron Light Bee. The #1 MX graphics brand in the USA. Available in Red/White/Blue, Blue, Green, Orange, Snow Camo. Premium UV-resistant vinyl, professional-grade OEM look.",why_popular:"Factory Effex is the most recognized name in MX graphics — riders who want the real factory look buy Factory Effex",compatibility:"Sur-Ron Light Bee X/S",image_url:"https://www.factoryeffex.com/cdn/shop/files/ebike-evo-blu.jpg?v=1757928048",amazon_direct:"https://www.factoryeffex.com/sur-ron-evographickit"},
  {id:"graphics-pinned-plate-decal",title:"Full Chrome/Color Front Plate Decal — Custom Name + Number (PinnedMotosport)",brand:"PinnedMotosport",category:"graphics",trending:9,retail_price:35,found_price:35,description:"Chrome and full-color holographic front number plate decals for Sur-Ron — fully personalized with your rider name, number, font style, and background color. Waterproof, durable laminate. Fits stock Sur-Ron plate and ODI Downhill plate. Ships fast.",why_popular:"The go-to for chrome and holographic plate decals — fully custom design, ships specifically made for the Sur-Ron front plate, no one else offers this finish at this price",compatibility:"Sur-Ron Light Bee X/S (stock number plate and ODI Downhill plate)",image_url:"https://pinnedmotosports.com/cdn/shop/files/il_fullxfull.5849962516_ozni.jpg",amazon_direct:"https://pinnedmotosports.com/products/full-color-chrome-sur-ron-front-plate-85301"},
  {id:"graphics-rideuxa-plate",title:"Pre-Designed ODI Number Plate Graphic — Sur-Ron (RideUXA X2)",brand:"RideUXA",category:"graphics",trending:9,retail_price:25,found_price:25,description:"Pre-designed front number plate graphic for the ODI DH plate on Sur-Ron — no need to design your own. Just pick the design, add your name and number, done. Printed on 21mil Substance Ultracurve® motocross-specific material with extra-strong adhesive. 100% designed and made in the USA.",why_popular:"The easiest way to get a pro-looking plate sticker — pre-made design ready to go, just enter your name and number, ships fast from the USA",compatibility:"ODI DH Number Plate — Sur-Ron Light Bee X/S, Talaria, Segway",image_url:"https://rideuxa.com/cdn/shop/files/UXA_SURRON_X2_30829faa-0584-4705-8a4d-815abf49809f.jpg?v=1724946347",amazon_direct:"https://rideuxa.com/products/surron-x2-number-plate-graphic"},

];

export const TRENDING = [...MODS].sort((a, b) => (b.trending || 0) - (a.trending || 0));

export const CATEGORIES = [...new Set(MODS.map(m => m.category))].sort();

export function searchMods(query) {
  const q = (query || '').toLowerCase().trim();
  if (!q) return TRENDING.slice(0, 50);
  const results = [];
  for (const mod of MODS) {
    let score = 0;
    const searchable = `${mod.title} ${mod.brand} ${mod.category} ${mod.description} ${mod.why_popular || ''}`.toLowerCase();
    if (searchable.includes(q)) score += 10;
    for (const word of q.split(' ')) {
      if (word && searchable.includes(word)) score += 3;
    }
    if (score > 0) results.push([score + (mod.trending || 0), mod]);
  }
  results.sort((a, b) => b[0] - a[0]);
  return results.map(([, m]) => m);
}
